# DATA PREPARATION

### Imports

In [1]:
# Essentials
import pandas as pd
import numpy as np

In [2]:
# Import custom class and functions
from lib.descriptors import QMDescriptors
from lib.utils import combine_data, format_compound_name, calculate_redox_potential

In [3]:
# Keep kernel updated 
%load_ext autoreload
%autoreload 2

### Load experimental data

In [4]:
# Read experimental data
file_experimental = 'data/TFKs_experimental_data.ods'
experimental = pd.read_excel(file_experimental)

In [5]:
# To avoid problems with MHC = 0, a small number is used instead
experimental.replace(0, 0.0001, inplace=True)

In [6]:
experimental['Name'] = experimental['Labjournal'].apply(format_compound_name)
experimental.head()

  Labjournal            Group Compounds (paper)  ...        MHC       LLE    Name
0    TFK-483          Nitrile                15  ...  11.505857  6.210000  TFK483
1    TFK-471        Halogenid                16  ...   0.453893  5.700000  TFK471
2    TFK-449        Halogenid                17  ...   0.935009  5.990000  TFK449
3    TFK-520  Carboxylic acid                19  ...   0.000100  3.484138  TFK520
4    TFK-543           Esters               21a  ...   2.583682  4.900000  TFK543

[5 rows x 13 columns]

### Extract local descriptors for nitro-BTZ core

The calculated QM properties are retrieved from the file generated by Jaguar (using `qm_descriptors.py` from Schr√∂dinger).

In [7]:
# Define file with QM properties
file_prop = 'data/TFKs_qm_descriptors.csv'
# Define file with atomic indices (given by Maestro)
file_atoms = 'data/TFKs_atoms.txt'

In [8]:
# retrieve descriptors
descriptors = QMDescriptors(file_prop, file_atoms)
atomic = descriptors.get_local_descriptors()

In [9]:
atomic

          cesp_C2  cesp_C4  cesp_C4a  ...   mul_O1   mul_O2   mul_S1
Name                                  ...
BTZ043    0.50010  0.69611   0.08219  ... -0.20075 -0.19977  0.21979
TFK449    0.49523  0.71525   0.00921  ... -0.20289 -0.19834  0.20474
TFK471    0.49527  0.74005  -0.12248  ... -0.20524 -0.19549  0.19534
TFK483    0.50982  0.69106   0.06901  ... -0.19678 -0.18834  0.23290
TFK520    0.50261  0.68648   0.09763  ... -0.20950 -0.20861  0.20248
TFK543    0.45402  0.64689   0.02258  ... -0.15415 -0.15632  0.18410
TFK659    0.47192  0.69895   0.10102  ... -0.20211 -0.20593  0.22671
TFK660    0.50020  0.70642   0.12861  ... -0.20427 -0.20203  0.23321
TFK661    0.47976  0.73760   0.07108  ... -0.20591 -0.20318  0.24380
TFK7092   0.49121  0.72835   0.09235  ... -0.19805 -0.19808  0.19030
TFK710    0.45820  0.71219   0.13859  ... -0.19803 -0.19912  0.19723
TFK718    0.52071  0.70248   0.05473  ... -0.20091 -0.19925  0.20946
TFK719    0.46978  0.72477   0.11144  ... -0.20104 -0.19709  0.20738
TFK726    0.47012  0.71890   0.11626  ... -0.20089 -0.19598  0.19427
TFK727    0.46910  0.71276   0.06547  ... -0.20428 -0.19818  0.19798
TFK746    0.51039  0.67363   0.04559  ... -0.20307 -0.20403  0.21877
dehalBTZ  0.47914  0.70417   0.10441  ... -0.20487 -0.21274  0.20342

[17 rows x 52 columns]

In [10]:
# Combine calculated properties with experimental values
atomic.reset_index(inplace=True, names='Name')
atomic_full = combine_data(atomic, experimental)
atomic_full.head()

TypeError: reset_index() got an unexpected keyword argument 'names'

### Extract global descriptors (CDFT)

In [11]:
# retrieve global descriptors
molecular = descriptors.get_global_descriptors()
molecular

,r_j_HOMO_Energy_Hartree,r_j_LUMO_Energy_Hartree,r_j_HOMO-LUMO_Gap_Hartree,Chemical_potential,Electrophilicity_index
Name,,,,,
BTZ043,-0.25982,-0.12815,0.13167,-0.193985,0.142896
dehalBTZ,-0.25523,-0.12213,0.13310,-0.188680,0.133735
TFK449,-0.25535,-0.12690,0.12845,-0.191125,0.142191
TFK471,-0.25188,-0.12591,0.12597,-0.188895,0.141626
TFK483,-0.26057,-0.12932,0.13125,-0.194945,0.144775
TFK520,-0.25026,-0.11962,0.13064,-0.184940,0.130905
TFK543,-0.25419,-0.12374,0.13045,-0.188965,0.136864
TFK659,-0.25688,-0.12524,0.13164,-0.191060,0.138651
TFK660,-0.25662,-0.12486,0.13176,-0.190740,0.138061
TFK661,-0.25608,-0.12381,0.13227,-0.189945,0.136384
TFK7092,-0.25862,-0.12542,0.13320,-0.192020,0.138407
TFK710,-0.25823,-0.12578,0.13245,-0.192005,0.139169
TFK718,-0.25812,-0.12541,0.13271,-0.191765,0.138550
TFK719,-0.25794,-0.12521,0.13273,-0.191575,0.138254
TFK726,-0.25770,-0.12563,0.13207,-0.191665,0.139076
TFK727,-0.25693,-0.12519,0.13174,-0.191060,0.138545
TFK746,-0.25344,-0.12434,0.12910,-0.188890,0.138185

In [12]:
# Combine the two dataframes
molecular.columns = molecular.columns.str.removeprefix('r_j_')
molecular.reset_index(inplace=True, names='Name')
molecular_full = combine_data(molecular, experimental)

In [13]:
# Add pMIC for M. smegmatis (for comparison later)
col = [x for x in experimental.columns if 'smeg' in x]
experimental['pMIC_Ms'] = -np.log10(experimental[col] / 1e6)

In [14]:
experimental.set_index('Name', inplace=True)
molecular_full.set_index('Name', inplace=True)
molecular_full = pd.concat((molecular_full, experimental[['clogP (SwissADME)', 
                                                          'pMIC_Ms']]), 
                           axis=1)
molecular_full.reset_index(inplace=True, names='Name')

In [15]:
molecular_full.head()

,Name,MIC_Mv,MIC_Ms,MHC,pMIC_Mv,pMHC,HOMO_Energy_Hartree,LUMO_Energy_Hartree,HOMO-LUMO_Gap_Hartree,Chemical_potential,Electrophilicity_index,clogP (SwissADME),pMIC_Ms
0,BTZ043,0.000348,0.058000,1.000000,9.458775,-0.000000,-0.25982,-0.12815,0.13167,-0.193985,0.142896,2.87,7.236572
1,dehalBTZ,1.100000,8.590000,0.000627,5.958607,3.202449,-0.25523,-0.12213,0.13310,-0.188680,0.133735,1.75,5.066007
2,TFK449,0.003618,0.056525,0.935009,8.441581,0.029184,-0.25535,-0.12690,0.12845,-0.191125,0.142191,2.45,7.247761
3,TFK471,0.006336,0.102190,0.453893,8.198200,0.343046,-0.25188,-0.12591,0.12597,-0.188895,0.141626,2.49,6.990591
4,TFK483,0.015963,0.128734,11.505857,7.796885,-1.060919,-0.26057,-0.12932,0.13125,-0.194945,0.144775,1.58,6.890307

In [16]:
experimental.reset_index(inplace=True, names='Name')

### Extract reaction energetics

In [17]:
# Read reaction energetics data (autodE)
file_dE = 'data/TFKs_reactivity_BH4_autode.csv'
reactivity = pd.read_csv(file_dE)
reactivity.sort_values(by='Cmpd', inplace=True)

In [18]:
# Rename without hyphen
reactivity.rename(columns={'Cmpd': 'Name'}, inplace=True)
reactivity['Name'] = reactivity.Name.apply(format_compound_name)
reactivity.head()

      Name         dE        dE‚Ä°         dG        dG‚Ä°
12  BTZ043   9.218489   8.724466   9.634038  15.263565
15  TFK449  10.471704   9.305760  11.048474  16.426274
7   TFK471  10.704600   9.231779  11.560231  16.295228
13  TFK483   6.262366   6.783300   7.301913  13.499660
1   TFK520  17.059218  12.291914  18.269437  19.740947

In [19]:
# Combine with experimental
reactivity_full = combine_data(reactivity, experimental)
reactivity_full.head()

,Name,MIC_Mv,MIC_Ms,MHC,pMIC_Mv,pMHC,dE,dE‚Ä°,dG,dG‚Ä°
0,BTZ043,0.000348,0.058000,1.000000,9.458775,-0.000000,9.218489,8.724466,9.634038,15.263565
1,TFK449,0.003618,0.056525,0.935009,8.441581,0.029184,10.471704,9.305760,11.048474,16.426274
2,TFK471,0.006336,0.102190,0.453893,8.198200,0.343046,10.704600,9.231779,11.560231,16.295228
3,TFK483,0.015963,0.128734,11.505857,7.796885,-1.060919,6.262366,6.783300,7.301913,13.499660
4,TFK520,0.980000,15.316755,0.000100,6.008774,4.000000,17.059218,12.291914,18.269437,19.740947

### Extract covalent docking data

In [20]:
# Read covalent docking data
covdock_file = 'data/TFKs_CovDock.csv'
covdock = pd.read_csv(covdock_file)

In [21]:
# Rename columns for simplicity
cols = ['Title', 'MMGBSA dG Bind', 'docking score']
covdock = covdock.loc[:, cols].copy()

In [22]:
# Rename without hyphen
covdock.rename(columns={'Title': 'Name'}, inplace=True)
covdock['Name'] = covdock.Name.apply(format_compound_name)
covdock.head()

     Name  MMGBSA dG Bind  docking score
0  BTZ043          -53.98         -7.011
1  TFK471          -47.94         -5.586
2  TFK449          -48.93         -5.553
3  TFK483          -51.66         -6.195
4  TFK520          -33.80         -5.107

In [23]:
# Combine with experimental
covdock_full = combine_data(covdock, experimental)
covdock_full.head()

,Name,MIC_Mv,MIC_Ms,MHC,pMIC_Mv,pMHC,MMGBSA dG Bind,docking score
0,BTZ043,0.000348,0.058000,1.000000,9.458775,-0.000000,-53.98,-7.011
1,TFK471,0.006336,0.102190,0.453893,8.198200,0.343046,-47.94,-5.586
2,TFK449,0.003618,0.056525,0.935009,8.441581,0.029184,-48.93,-5.553
3,TFK483,0.015963,0.128734,11.505857,7.796885,-1.060919,-51.66,-6.195
4,TFK520,0.980000,15.316755,0.000100,6.008774,4.000000,-33.80,-5.107

### Extract permeability data

In [24]:
# Read permeability data
perm_file = 'data/TFKs_membrane_perm.csv'
perm = pd.read_csv(perm_file)

In [25]:
# Rename without hyphen
perm.rename(columns={'title': 'Name'}, inplace=True)
perm['Name'] = perm.Name.apply(format_compound_name)
perm.head()

,Name,r_adme_Log_Perm_RRCK,r_adme_Membrane_dG_Insert,r_adme_Membrane_Penalty,r_adme_Membrane_HDLD,r_adme_Membrane_Energy,r_adme_Solvent_Energy,r_adme_Membrane_GB,r_adme_Solvent_GB,r_adme_Volume,r_adme_Membrane_HDLD_GB
0,BTZ043,-4.539085,1.178409,0.1028,1.075609,-3.844548,-4.920157,-3.127464,-10.319747,707.770699,7.192283
1,TFK449,-4.590030,3.014551,0.1447,2.869851,-9.659625,-12.529475,-3.159509,-9.768251,671.756133,6.608742
2,TFK471,-4.652516,4.082418,0.2748,3.807618,-3.290078,-7.097697,-2.973296,-9.485235,677.490823,6.511939
3,TFK483,-4.646541,4.159544,0.0255,4.134044,1.906698,-2.227346,-4.494394,-12.304219,693.816791,7.809824
4,TFK520,-5.842402,17.529522,6.6327,10.896822,-10.130156,-21.026978,-5.418847,-19.573772,705.272627,14.154925

In [26]:
# Combine with experimental
perm_full = combine_data(perm, experimental)
perm_full.head()

,Name,MIC_Mv,MIC_Ms,MHC,pMIC_Mv,pMHC,r_adme_Log_Perm_RRCK,r_adme_Membrane_dG_Insert,r_adme_Membrane_Penalty,r_adme_Membrane_HDLD,r_adme_Membrane_Energy,r_adme_Solvent_Energy,r_adme_Membrane_GB,r_adme_Solvent_GB,r_adme_Volume,r_adme_Membrane_HDLD_GB
0,BTZ043,0.000348,0.058000,1.000000,9.458775,-0.000000,-4.539085,1.178409,0.1028,1.075609,-3.844548,-4.920157,-3.127464,-10.319747,707.770699,7.192283
1,TFK449,0.003618,0.056525,0.935009,8.441581,0.029184,-4.590030,3.014551,0.1447,2.869851,-9.659625,-12.529475,-3.159509,-9.768251,671.756133,6.608742
2,TFK471,0.006336,0.102190,0.453893,8.198200,0.343046,-4.652516,4.082418,0.2748,3.807618,-3.290078,-7.097697,-2.973296,-9.485235,677.490823,6.511939
3,TFK483,0.015963,0.128734,11.505857,7.796885,-1.060919,-4.646541,4.159544,0.0255,4.134044,1.906698,-2.227346,-4.494394,-12.304219,693.816791,7.809824
4,TFK520,0.980000,15.316755,0.000100,6.008774,4.000000,-5.842402,17.529522,6.6327,10.896822,-10.130156,-21.026978,-5.418847,-19.573772,705.272627,14.154925

### Calculate redox potentials

In [27]:
# Read energies from redox calculations (autodE)
file_energies = 'data/TFKs_redox_autode.csv'
redox = calculate_redox_potential(file_energies)

In [28]:
# Rename without hyphen
redox['Name'] = redox.Name.apply(format_compound_name)
redox.head()

     Name  dG_aq (Ha)  Ered (V)
0  BTZ043   -0.138759  3.774525
1  TFK449   -0.137629  3.743783
2  TFK471   -0.136911  3.724270
3  TFK483   -0.140240  3.814829
4  TFK520   -0.135824  3.694697

In [29]:
redox_full = combine_data(redox, experimental)
redox_full.head()

,Name,MIC_Mv,MIC_Ms,MHC,pMIC_Mv,pMHC,dG_aq (Ha),Ered (V)
0,BTZ043,0.000348,0.058000,1.000000,9.458775,-0.000000,-0.138759,3.774525
1,TFK449,0.003618,0.056525,0.935009,8.441581,0.029184,-0.137629,3.743783
2,TFK471,0.006336,0.102190,0.453893,8.198200,0.343046,-0.136911,3.724270
3,TFK483,0.015963,0.128734,11.505857,7.796885,-1.060919,-0.140240,3.814829
4,TFK520,0.980000,15.316755,0.000100,6.008774,4.000000,-0.135824,3.694697

In [32]:
redox_full['E_vs_SHE'] = redox_full['Ered (V)'] - 4.28 # reference value

## Save compiled data

In [33]:
# Define dataframes
dfs = [atomic_full, molecular_full, reactivity_full, 
       covdock_full, perm_full, redox_full]
# Define labels
labels = ['Atomic', 'Molecular', 'Reactivity', 
          'CovDock', 'Permeability', 'Redox']

# Save all dfs to unique Excel file
with pd.ExcelWriter('results/Full_SI_datasets.xlsx') as writer:
    for df, lab in zip(dfs, labels):
        df.to_excel(writer, sheet_name=lab, index=False)